In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 15.7 ms, sys: 11.1 ms, total: 26.8 ms
Wall time: 35.5 ms


In [7]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 587 ms, sys: 176 ms, total: 763 ms
Wall time: 779 ms


## 4.1 The NumPy ndarray: A Multidimensional Array Object (p. 87)

In [8]:
# Generate some random data
data = np.random.randn(2, 3)

In [9]:
data

array([[-0.1521902 ,  1.27560253,  0.03997207],
       [ 0.34660165, -0.9244022 , -0.04723577]])

In [10]:
data * 10

array([[-1.52190205, 12.75602534,  0.39972068],
       [ 3.46601646, -9.24402201, -0.4723577 ]])

In [11]:
data + data

array([[-0.30438041,  2.55120507,  0.07994414],
       [ 0.69320329, -1.8488044 , -0.09447154]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

## Creating ndarrays

In [ ]:
data1 = [6, 7.5, 8, 0, 1]