In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 15.7 ms, sys: 11.1 ms, total: 26.8 ms
Wall time: 35.5 ms


In [7]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 587 ms, sys: 176 ms, total: 763 ms
Wall time: 779 ms


## 4.1 The NumPy ndarray: A Multidimensional Array Object (p. 87)

In [8]:
# Generate some random data
data = np.random.randn(2, 3)

In [9]:
data

array([[-0.1521902 ,  1.27560253,  0.03997207],
       [ 0.34660165, -0.9244022 , -0.04723577]])

In [10]:
data * 10

array([[-1.52190205, 12.75602534,  0.39972068],
       [ 3.46601646, -9.24402201, -0.4723577 ]])

In [11]:
data + data

array([[-0.30438041,  2.55120507,  0.07994414],
       [ 0.69320329, -1.8488044 , -0.09447154]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

## Creating ndarrays (p.88)

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int64')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[ 1.28822975e-231, -2.00390493e+000],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  1.16095484e-028]],

       [[ 6.97283618e+228,  3.68008723e-110],
        [ 6.48224638e+170,  3.67145870e+228],
        [ 1.35373534e+295,  8.34402697e-309]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])