In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 14.6 ms, sys: 10.9 ms, total: 25.5 ms
Wall time: 31.5 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 627 ms, sys: 165 ms, total: 792 ms
Wall time: 869 ms


## 4.1 The NumPy ndarray: A Multidimensional Array Object (p. 87)

In [7]:
# Generate some random data
data = np.random.randn(2, 3)

In [8]:
data

array([[-0.31025338,  2.3557416 ,  1.62836264],
       [-0.83241051, -0.01187957,  0.7459673 ]])

In [9]:
data * 10

array([[-3.10253381, 23.55741599, 16.28362639],
       [-8.32410506, -0.11879571,  7.45967298]])

In [10]:
data + data

array([[-0.62050676,  4.7114832 ,  3.25672528],
       [-1.66482101, -0.02375914,  1.4919346 ]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

## Creating ndarrays (p.88)

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2, 3, 2))

array([[[1.72723371e-077, 1.72723371e-077],
        [2.96439388e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[1.72723371e-077, 1.72723371e-077],
        [1.48219694e-323, 0.00000000e+000],
        [0.00000000e+000, 8.34402697e-309]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays (p 90)

In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [28]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(['1.25', '9.6', '42'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25,  9.6 , 42.  ])

In [40]:
int_array = np.arange(10)

In [41]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [42]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
empty_uint32 = np.empty(8, dtype='u4')

In [44]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## Arithmatic with NumPy Arrays (p. 93)

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [46]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [52]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing (p. 94)

In [54]:
arr = np.arange(10)

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[5]

5

In [57]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[5:8] = 12

In [59]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [60]:
arr_slice = arr[5:8]

In [61]:
arr_slice

array([12, 12, 12])

In [62]:
arr_slice[1] = 12345

In [63]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [64]:
arr_slice[:] = 64

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0, 2]

3

In [70]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
old_values = arr3d[0].copy()

In [74]:
arr3d[0] = 42

In [75]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[0] = old_values

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1, 0]

array([7, 8, 9])

In [79]:
x = arr3d[1]

In [80]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [81]:
x[0]

array([7, 8, 9])

### Indexing with slices (p. 97)

In [82]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [83]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [84]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [87]:
arr2d[1, :2]

array([4, 5])

In [88]:
arr2d[:2, 2]

array([3, 6])

In [89]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [90]:
arr2d[:2, 1:] = 0

In [91]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing (p. 99)

In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [93]:
data = np.random.randn(7, 4)

In [94]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [95]:
data

array([[ 0.35894829, -0.95555187,  0.14674483, -1.11510135],
       [ 0.33272042,  1.5000764 ,  0.67082347, -0.50833886],
       [ 0.27982315,  0.17855651, -0.53683854,  1.25286205],
       [-1.79464097, -0.48861922,  0.61784705,  1.30318921],
       [ 1.08795014, -2.16147922,  0.03018314, -2.63076844],
       [ 1.08753322, -0.47697533, -1.16199889,  1.40883644],
       [-0.62784438, -0.86660007, -1.07847707,  0.47879157]])

In [96]:
data[names == 'Bob']

array([[ 0.35894829, -0.95555187,  0.14674483, -1.11510135],
       [-1.79464097, -0.48861922,  0.61784705,  1.30318921]])

In [97]:
data[names == 'Bob', 2:]

array([[ 0.14674483, -1.11510135],
       [ 0.61784705,  1.30318921]])

In [98]:
data[names == 'Bob', 3]

array([-1.11510135,  1.30318921])

In [99]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [100]:
data[~(names == 'Bob')]

array([[ 0.33272042,  1.5000764 ,  0.67082347, -0.50833886],
       [ 0.27982315,  0.17855651, -0.53683854,  1.25286205],
       [ 1.08795014, -2.16147922,  0.03018314, -2.63076844],
       [ 1.08753322, -0.47697533, -1.16199889,  1.40883644],
       [-0.62784438, -0.86660007, -1.07847707,  0.47879157]])

In [101]:
cond = names == 'Bob'

In [102]:
data[~cond]

array([[ 0.33272042,  1.5000764 ,  0.67082347, -0.50833886],
       [ 0.27982315,  0.17855651, -0.53683854,  1.25286205],
       [ 1.08795014, -2.16147922,  0.03018314, -2.63076844],
       [ 1.08753322, -0.47697533, -1.16199889,  1.40883644],
       [-0.62784438, -0.86660007, -1.07847707,  0.47879157]])

In [103]:
mask = (names == 'Bob') | (names == 'Will')

In [104]:
mask

array([ True, False,  True,  True,  True, False, False])

In [105]:
data[mask]

array([[ 0.35894829, -0.95555187,  0.14674483, -1.11510135],
       [ 0.27982315,  0.17855651, -0.53683854,  1.25286205],
       [-1.79464097, -0.48861922,  0.61784705,  1.30318921],
       [ 1.08795014, -2.16147922,  0.03018314, -2.63076844]])

In [106]:
data[data < 0] = 0

In [107]:
data

array([[0.35894829, 0.        , 0.14674483, 0.        ],
       [0.33272042, 1.5000764 , 0.67082347, 0.        ],
       [0.27982315, 0.17855651, 0.        , 1.25286205],
       [0.        , 0.        , 0.61784705, 1.30318921],
       [1.08795014, 0.        , 0.03018314, 0.        ],
       [1.08753322, 0.        , 0.        , 1.40883644],
       [0.        , 0.        , 0.        , 0.47879157]])

In [108]:
data[names != 'Joe'] = 7

In [109]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.33272042, 1.5000764 , 0.67082347, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.08753322, 0.        , 0.        , 1.40883644],
       [0.        , 0.        , 0.        , 0.47879157]])

## Fancy Indexing (p. 102)

In [110]:
arr = np.empty((8, 4))

In [111]:
for i in range(8):
    arr[i] = i

In [112]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [113]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [114]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [115]:
arr = np.arange(32).reshape((8, 4))

In [116]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [117]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [118]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes (p. 103)

In [119]:
arr = np.arange(15).reshape((3, 5))

In [120]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [122]:
arr = np.random.randn(6, 3)

In [123]:
arr

array([[ 1.21011574, -0.6351481 , -0.73719688],
       [ 1.66536309,  0.94324994,  1.24170616],
       [-0.26369122, -1.77005202,  0.03118575],
       [ 0.48402045, -0.0158068 ,  1.14886292],
       [ 0.77345727, -0.19451562, -0.97083537],
       [-0.32762443, -1.46586382, -0.76047128]])

In [124]:
np.dot(arr.T, arr)

array([[5.24719708, 1.59115056, 1.22189709],
       [1.59115056, 6.61306061, 2.86969818],
       [1.22189709, 2.86969818, 4.92698989]])

In [125]:
arr = np.arange(16).reshape((2, 2, 4))

In [126]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [127]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [128]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [129]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 4.2 Universal Functions: Fast Element-Wise Array Functions (p. 105)

In [130]:
arr = np.arange(10)

In [131]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [133]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [134]:
x = np.random.randn(8)

In [135]:
y = np.random.randn(8)

In [136]:
x

array([ 0.14702019,  0.02239675,  0.64623986, -0.45714338, -1.27184924,
       -0.11741027, -0.31775903, -0.41015022])

In [137]:
y

array([-1.80617427,  0.43022968,  0.57773797, -1.20640422,  0.56501098,
       -0.09364073,  0.64025468,  1.35355523])

In [138]:
np.maximum(x, y)

array([ 0.14702019,  0.43022968,  0.64623986, -0.45714338,  0.56501098,
       -0.09364073,  0.64025468,  1.35355523])

In [139]:
arr = np.random.randn(7) * 5

In [140]:
arr

array([-11.56117536, -10.71523502,  -0.17132688,  -1.62841693,
        -4.5277785 ,  -6.83664883,   2.43203595])

In [141]:
remainder, whole_part = np.modf(arr)

In [142]:
remainder

array([-0.56117536, -0.71523502, -0.17132688, -0.62841693, -0.5277785 ,
       -0.83664883,  0.43203595])

In [143]:
whole_part

array([-11., -10.,  -0.,  -1.,  -4.,  -6.,   2.])

In [144]:
arr

array([-11.56117536, -10.71523502,  -0.17132688,  -1.62841693,
        -4.5277785 ,  -6.83664883,   2.43203595])

In [146]:
np.sqrt(arr)

<ipython-input-146-038265ba92f5>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan,        nan,        nan,        nan,
              nan, 1.55949862])

In [147]:
np.sqrt(arr, arr)

<ipython-input-147-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan,        nan,        nan,        nan,
              nan, 1.55949862])

## 4.3 Array-Oriented Programming with Arrays (p. 108)