In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 13.4 ms, sys: 8.55 ms, total: 21.9 ms
Wall time: 21.1 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 590 ms, sys: 148 ms, total: 738 ms
Wall time: 747 ms


## 4.1 The NumPy ndarray: A Multidimensional Array Object (p. 87)

In [7]:
# Generate some random data
data = np.random.randn(2, 3)

In [8]:
data

array([[-0.61487252,  0.54032139, -0.14053139],
       [ 0.93304898,  0.58703861,  0.80550404]])

In [9]:
data * 10

array([[-6.1487252 ,  5.40321393, -1.4053139 ],
       [ 9.33048982,  5.87038613,  8.05504041]])

In [10]:
data + data

array([[-1.22974504,  1.08064279, -0.28106278],
       [ 1.86609796,  1.17407723,  1.61100808]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

## Creating ndarrays (p.88)

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2, 3, 2))

array([[[-1.72723371e-077, -1.72723371e-077],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  1.16095484e-028]],

       [[ 6.97283618e+228,  4.50603893e-144],
        [ 4.82412328e+228,  1.04718130e-142],
        [ 3.99911070e+252,  8.34402697e-309]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays (p 90)

In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [28]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(['1.25', '9.6', '42'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25,  9.6 , 42.  ])

In [40]:
int_array = np.arange(10)

In [43]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [44]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
empty_uint32 = np.empty(8, dtype='u4')

In [46]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## Arithmatic with NumPy Arrays (p. 93)